version: '3.8'

services:
  llm:
    image: ollama/ollama
    container_name: fe-llm
    ports:
      - "11434:11434"
    environment:
      - CODER_MODEL=qwen2.5-coder:3b
      - VISION_MODEL=qwen2.5vl:3b
    volumes:
      - ./ollama-data:/root/.ollama           # storage model
      - ./ollama-init.sh:/usr/local/bin/ollama-init.sh
    entrypoint: ["/usr/local/bin/ollama-init.sh"]
